name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Verify AWS
        run: aws sts get-caller-identity
      
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build and push
        run: |
          docker build -t 871499496674.dkr.ecr.us-east-1.amazonaws.com/myapp:latest .
          docker push 871499496674.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
      
      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name cloud-native-cluster --region us-east-1
          kubectl rollout restart deployment myapp
